"""second updates time

Revision ID: 31675da85cb4
Revises: 1e14ee56fce8
Create Date: 2018-09-15 17:03:48.724127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31675da85cb4'
down_revision = '1e14ee56fce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_date_created'), 'post', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_date_created'), table_name='post')
    # ### end Alembic commands ###
