"""updates datetime

Revision ID: 513bb2a9bded
Revises: 7d4100eca63d
Create Date: 2018-09-16 17:41:51.299474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513bb2a9bded'
down_revision = '7d4100eca63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_index('ix_post_date_created', table_name='post')
    op.drop_column('post', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_post_date_created', 'post', ['date_created'], unique=False)
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
