"""thrid updates time

Revision ID: 7d4100eca63d
Revises: 31675da85cb4
Create Date: 2018-09-15 17:08:45.130099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4100eca63d'
down_revision = '31675da85cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.drop_index('ix_comments_date_created', table_name='comments')
    op.drop_column('comments', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_comments_date_created', 'comments', ['date_created'], unique=False)
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
